version: '3.8'

services:
  backend:
    build: ./backend
    container_name: comp3133_backend
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: always

  frontend:
    build: ./frontend
    container_name: comp3133_frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: always